name: Fill Localization

on: push

jobs:
  build:
    name: Fill Localization
    runs-on: ubuntu-latest
    if: github.actor != 'my_bot_account'
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: mod

      - name: Checkout Localizer
        uses: actions/checkout@v3
        with:
          repository: JohN100x1/IsekaiLocalizer
          path: localizer

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Setup Poetry
        run: pip install poetry

      - name: Run localization script
        run: |
          cd localizer
          poetry install
          poetry run python src/main.py mod/IsekaiMod/Localization/LocalizationPack.json

      - name: Push Changes
        run: |
          cd mod
          git add .
          git commit -m "feat:\ update LocalizationPack.json"
          git push origin HEAD:${{ github.ref }}